install:
    - sudo apt-get install texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended 
    - sudo apt-get install chktex

script:
    # SpellCheck
    # Lint
    - chktex -W
    - chktex -q -n 12 -n 36 -n 2 -n 8 sintese.tex 2>/dev/null | tee lint.out
    - test ! -s lint.out
    # Compile
    #- pdflatex *.tex
    # Publish pdf
