install:
- sudo apt-get install texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended
- sudo apt-get install chktex rubber
script:
- chktex -W
- chktex -q -n 12 -n 36 -n 2 -n 8 sintese.tex 2>/dev/null | tee lint.out
- test ! -s lint.out
- mkdir build && rubber --into build --pdf --warn all sintese.tex
branches:
  only:
    - master
after_success:
- ./deploy.sh --verbose
